import {
  siReact,
  siNextdotjs,
  siTypescript,
  siTailwindcss,
  siSanity,
  siCss,
  siNodedotjs,
  siExpress,
  siNestjs,
  siJavascript,
  siPython,
  siClaude,
  siResend,
  siPostgresql,
  siMysql,
  siMongodb,
  siRedis,
  siMongoose,
  siKnexdotjs,
  siSupabase,
  siGit,
  siPostman,
  siSwagger,
  siDocker,
  siVercel,
} from "simple-icons";

export const stackIconPaths: Record<string, string> = {
  React: siReact.path,
  "Next.js": siNextdotjs.path,
  TypeScript: siTypescript.path,
  "Tailwind CSS": siTailwindcss.path,
  Sanity: siSanity.path,
  CSS: siCss.path,
  "Node.js": siNodedotjs.path,
  Express: siExpress.path,
  NestJS: siNestjs.path,
  JavaScript: siJavascript.path,
  Python: siPython.path,
  Claude: siClaude.path,
  Resend: siResend.path,
  PostgreSQL: siPostgresql.path,
  MySQL: siMysql.path,
  MongoDB: siMongodb.path,
  Redis: siRedis.path,
  Mongoose: siMongoose.path,
  Knex: siKnexdotjs.path,
  Supabase: siSupabase.path,
  Git: siGit.path,
  Postman: siPostman.path,
  Swagger: siSwagger.path,
  Docker: siDocker.path,
  Vercel: siVercel.path,
};
